"use client";

import React, { useEffect, useState } from "react";
import { Navbar } from "@/components/nav/navbar";
import { LearnerProgressHeader } from "@/components/learning/learner-progress-header";
import { ActivePlanView } from "@/components/learning/active-plan-view";
import { AgentActivityPanel } from "@/components/agent/agent-activity-panel";
import { LessonViewerModal } from "@/components/learning/lesson-viewer-modal";
import { invokeWebMCPTool, registerVerbatimWebMCPTools } from "@/lib/webmcp";
import { learningStore, LearningState } from "@/lib/learning-store";
import { BottomGraphic } from "@/components/home/bottom-graphic";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export default function MyLearningPage() {
  const [storeState, setStoreState] = useState<LearningState>(learningStore.getState());
  const [openedLessonId, setOpenedLessonId] = useState<string | null>(null);

  useEffect(() => {
    // Ensure tools are registered here too just in case they navigated directly
    registerVerbatimWebMCPTools();

    const unsubscribe = learningStore.subscribe(() => {
      const current = learningStore.getState();
      setStoreState(current);
      if (current.currentLesson) {
        setOpenedLessonId(current.currentLesson);
      }
    });

    return () => unsubscribe();
  }, []);

  const handleOpenLesson = (lessonId: string) => {
    invokeWebMCPTool("open_lesson", { lessonId });
  };

  return (
    <div className="min-h-screen bg-[#FAFCF9] text-neutral-900 flex flex-col selection:bg-primary-100 selection:text-primary-800">
      <Navbar
        items={[
          { label: "Courses", href: "/courses", active: false },
          { label: "My Learning", href: "/my-learning", active: true },
        ]}
      />

      <main className="flex-1 flex flex-col max-w-6xl mx-auto w-full px-4 sm:px-6 pt-8 pb-16">
        <LearnerProgressHeader />

        <div className="mt-8 mb-4">
          <h1 className="font-serif text-3xl sm:text-4xl text-neutral-900 font-normal tracking-tight mb-2">
            My Learning
          </h1>
          <p className="text-neutral-600">
            Track your progress and follow the personalized plans generated by your Agent.
          </p>
        </div>

        {storeState.activePlan ? (
          <div className="mb-12">
            <ActivePlanView
              plan={storeState.activePlan}
              onOpenLesson={handleOpenLesson}
            />
          </div>
        ) : (
          <div className="mb-12 py-16 px-6 bg-white border border-neutral-200/80 rounded-2xl text-center shadow-xs">
            <div className="max-w-md mx-auto">
              <h3 className="font-serif text-xl sm:text-2xl text-neutral-900 mb-3">
                No active plan yet
              </h3>
              <p className="text-neutral-500 mb-6 leading-relaxed">
                You don't have a learning plan right now. Ask your WebMCP Agent to create a personalized curriculum based on your goals, or browse our courses to start manually.
              </p>
              <Link
                href="/courses"
                className="inline-flex items-center gap-2 h-10 rounded-full bg-primary-600 px-6 text-sm font-medium text-white shadow-sm transition-colors hover:bg-primary-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 cursor-pointer"
              >
                Browse Courses
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 gap-6">
          <AgentActivityPanel />
        </div>
      </main>

      <LessonViewerModal
        lessonId={openedLessonId}
        onClose={() => {
          setOpenedLessonId(null);
          learningStore.setCurrentLesson(null);
        }}
      />
      <BottomGraphic />
    </div>
  );
}
